language: generic


sudo: required
services: docker
dist: bionic

install:
  - source texlive.sh


cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


script: 
  - l3build install && l3build ctan -H --show-log-on-error

deploy:
  - provider: releases
    api_key:
      secure: MOtP1n9ZV48lSqltrlcuzl0KVHiRw+7k4lld6Ml5lD0CDj9FWtGWThfxNAjb8tgHel1sRkgOBlR9pmvLX6E/STkRpRP16HnYhGggEED/8Eq2a3IIoDelwYi/vODoxo2wesxcG2lM0j4ZzgyBvDqTlbG0qLcKiBHJuZFc8YNpoLB133tuWMMMlAB4hK7xms9SYwoBgT/xpXjjXYa1aUdsICaxlZM9OCP+SCEOJr2TcpwbFxlmIBhATOx1aMbEKoS94zEJY0NZGX5v71wBhZ8kQE9vcMJk3UtzuwlsRAspeFrQtLnMt4NfI4Bz0M53pkzVe59ShTOxINMdCccEF88Kfp13OPBbDcOGy1YIJ7keKzl25mUAltS5kZ40HlIt++r/VVi/FvOImGVPFZk/iL6t3OT4LlW0FcRABNtjVmIrFTFp8u6EqGCFT8op5YQPnOPCfWtbI6K5iMvm3sEAY39/+z26ui8jQa7zsCfnFlMW63kr01eNDpzGzRbSaVwPqgCQdKlLQlg/Ss64ihu6Wd/PwOmItgMaTSb1a8D4ju2u5MidsCTrdre2spHT+R+P5K2Bf+JPEmdJXe/d6tYqz+vCDcpDFyoMIGVMm0M/zQGmxvfALvzp6fqGA24RcqvY/bX/RH0psHMFHe+/rTxYwMixl9QhgDUvmxV+3ezNg28+aEM=
    file_glob: true
    file:
      - build/distrib/ctan/*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG == *-dev
    prerelease: true
  - provider: releases
    api_key:
      secure: MOtP1n9ZV48lSqltrlcuzl0KVHiRw+7k4lld6Ml5lD0CDj9FWtGWThfxNAjb8tgHel1sRkgOBlR9pmvLX6E/STkRpRP16HnYhGggEED/8Eq2a3IIoDelwYi/vODoxo2wesxcG2lM0j4ZzgyBvDqTlbG0qLcKiBHJuZFc8YNpoLB133tuWMMMlAB4hK7xms9SYwoBgT/xpXjjXYa1aUdsICaxlZM9OCP+SCEOJr2TcpwbFxlmIBhATOx1aMbEKoS94zEJY0NZGX5v71wBhZ8kQE9vcMJk3UtzuwlsRAspeFrQtLnMt4NfI4Bz0M53pkzVe59ShTOxINMdCccEF88Kfp13OPBbDcOGy1YIJ7keKzl25mUAltS5kZ40HlIt++r/VVi/FvOImGVPFZk/iL6t3OT4LlW0FcRABNtjVmIrFTFp8u6EqGCFT8op5YQPnOPCfWtbI6K5iMvm3sEAY39/+z26ui8jQa7zsCfnFlMW63kr01eNDpzGzRbSaVwPqgCQdKlLQlg/Ss64ihu6Wd/PwOmItgMaTSb1a8D4ju2u5MidsCTrdre2spHT+R+P5K2Bf+JPEmdJXe/d6tYqz+vCDcpDFyoMIGVMm0M/zQGmxvfALvzp6fqGA24RcqvY/bX/RH0psHMFHe+/rTxYwMixl9QhgDUvmxV+3ezNg28+aEM=
    file_glob: true
    file:
      - build/distrib/ctan/*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG != *-dev
    prerelease: false
